services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: discordbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  bot:
    build:
      context: .
      target: dev
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app:z
  redis:
    image: redis:8

volumes:
  db_data: